config/routes.rb
Rails.application.routes.draw do
  resources :pseudos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pseudo.rb
class Pseudo < ApplicationRecord


  validates :pseudo, presence: true
  validates :pseudo, format: { with: /\A[A-Z]+\Z/,
    message: "only allows upper letters" }
  validates :pseudo, length: {is: 3}
  validates :pseudo, uniqueness: true

  #after_validation :uniqueness_pseudo

  before_save :uppercase_pseudo

  def uppercase_pseudo
      pseudo.upcase!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pseudos_controller.rb
class PseudosController < ApplicationController
  before_action :set_pseudo, only: [:show, :edit, :update, :destroy]

  # GET /pseudos
  # GET /pseudos.json
  def index
    @pseudos = Pseudo.all
  end

  # GET /pseudos/1
  # GET /pseudos/1.json
  def show
  end

  # GET /pseudos/new
  def new
    @pseudo = Pseudo.new
  end

  # GET /pseudos/1/edit
  def edit
  end

  def generate_pseudo
    o = [('A'..'Z')].map(&:to_a).flatten
    string = (0...3).map { o[rand(o.length)] }.join

    @pseudo = Pseudo.new(:pseudo => string)

      if @pseudo.save
        respond_to do |format|
        format.html { redirect_to @pseudo, notice: 'OK, your pseudo was successfully created.' }
        format.json { render :show, status: :created, location: @pseudo }
        end
      else
        generate_pseudo
        #format.html { render :new }
        #format.json { render json: @pseudo.errors, status: :unprocessable_entity }
      end
  end

  # POST /pseudos
  # POST /pseudos.json

  def create

    @pseudo = Pseudo.new(pseudo_params)
      if @pseudo.save
        respond_to do |format|
        format.html { redirect_to @pseudo, notice: 'OK, your pseudo was successfully created.' }
        format.json { render :show, status: :created, location: @pseudo }
        end
      elsif @pseudo.pseudo.length < 3
        respond_to do |format|
        format.html { render :new }
        format.json { render json: @pseudo.errors, status: :unprocessable_entity }
      end
      else
        generate_pseudo
      end
  end

  # PATCH/PUT /pseudos/1
  # PATCH/PUT /pseudos/1.json
  def update
    respond_to do |format|
      if @pseudo.update(pseudo_params)
        format.html { redirect_to @pseudo, notice: 'OK, your pseudo was successfully updated.' }
        format.json { render :show, status: :ok, location: @pseudo }
      else
        format.html { render :edit }
        format.json { render json: @pseudo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pseudos/1
  # DELETE /pseudos/1.json
  def destroy
    @pseudo.destroy
    respond_to do |format|
      format.html { redirect_to pseudos_url, notice: 'OK, your pseudo was successfully destroyed.' }
      format.json { head :no_content, status: 'SUCCESS'}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pseudo
      @pseudo = Pseudo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pseudo_params
      params.require(:pseudo).permit(:pseudo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pseudos_helper.rb
module PseudosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PseudoRand</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pseudos/_form.html.erb
<%= form_with(model: pseudo, local: true) do |form| %>
  <% if pseudo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pseudo.errors.count, "error") %> prohibited this pseudo from being saved:</h2>

      <ul>
      <% pseudo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pseudo %>
    <%= form.text_field :pseudo, maxlength: 3 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pseudos/edit.html.erb
<h1>Editing Pseudo</h1>

<%= render 'form', pseudo: @pseudo %>

<%= link_to 'Show', @pseudo %> |
<%= link_to 'Back', pseudos_path %>

app/views/pseudos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pseudos</h1>

<table>
  <thead>
    <tr>
      <th>Pseudo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pseudos.each do |pseudo| %>
      <tr>
        <td><%= pseudo.pseudo %></td>
        <td><%= link_to 'Show', pseudo %></td>
        <td><%= link_to 'Edit', edit_pseudo_path(pseudo) %></td>
        <td><%= link_to 'Destroy', pseudo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pseudo', new_pseudo_path %>

app/views/pseudos/new.html.erb
<h1>New Pseudo</h1>

<%= render 'form', pseudo: @pseudo %>

<%= link_to 'Back', pseudos_path %>

app/views/pseudos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pseudo:</strong>
  <%= @pseudo.pseudo %>
</p>

<%= link_to 'Edit', edit_pseudo_path(@pseudo) %> |
<%= link_to 'Back', pseudos_path %>